name: notes_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3

  # Firebase core (required)
  firebase_core: ^2.24.2

  # Firebase services
  firebase_auth: ^4.15.3          # For user authentication
  cloud_firestore: ^4.13.6       # For database
  firebase_storage: ^11.5.6      # For file storage (optional)

  # UI and state management
  provider: ^6.1.1               # State management
  shared_preferences: ^2.2.2     # Local storage
  intl: ^0.18.1                  # Date formatting

  # Additional helpful packages
  flutter_signin_button: ^2.0.0  # Pre-built sign-in buttons
  loading_animation_widget: ^1.2.0  # Loading indicators

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true